MasterScripter/MasterScripter/Controllers/CommentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Security.AntiXss;
using MasterScripter.BL.Utils;
using MasterScripter.DAL.Models;
using MasterScripter.Models;

namespace MasterScripter.Controllers
{
    [Authorize]
    [ConnectedUserFilterAttribute]

    public class CommentsController : Controller
    {
        private MasterScripterContext db = new MasterScripterContext();

        // GET: Comments
        public ActionResult Index()
        {
            var comments = db.Comments.Include(c => c.Execution).Include(c => c.User);

            ViewBag.CurrentUser = db.Users.FirstOrDefault(u => u.Email.Equals(User.Identity.Name));
            return View(comments.ToList());
        }

        public ActionResult CommentsByExecution(int executionid)
        {
            var comments = db.Comments.Where(c=>c.ExecutionId==executionid).Include(c => c.Execution).Include(c => c.User);
            ViewBag.CurrentUser = db.Users.FirstOrDefault(u => u.Email.Equals(User.Identity.Name));

            return PartialView("Index",comments.ToList());
        }

        public ActionResult GetConversion(int executionid)
        {
            ViewBag.Executionid = executionid;
            return PartialView("Conversion");
        }

        // GET: Comments/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        // GET: Comments/Create
        public ActionResult Create()
        {
            ViewBag.ExecutionId = new SelectList(db.Executions, "Id", "Id");
            ViewBag.UserId = new SelectList(db.Users, "Id", "FullName");
            return View();
        }

        // POST: Comments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Content,CreationDate,UserId,ExecutionId")] Comment comment)
        {
            if (ModelState.IsValid)
            {
                var user = db.Users.FirstOrDefault(u => u.Email.Equals(User.Identity.Name));

                comment.UserId = user.Id;
                comment.CreationDate = DateTime.Now;
                db.Comments.Add(comment);
                db.SaveChanges();
            }

            return Content("OK");
        }

        // GET: Comments/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            ViewBag.ExecutionId = new SelectList(db.Executions, "Id", "MachineIP", comment.ExecutionId);
            ViewBag.UserId = new SelectList(db.Users, "Id", "FullName", comment.UserId);
            return View(comment);
        }

        // POST: Comments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Content,CreationDate,UserId,ExecutionId")] Comment comment)
        {
            if (ModelState.IsValid)
            {
                db.Entry(comment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ExecutionId = new SelectList(db.Executions, "Id", "MachineIP", comment.ExecutionId);
            ViewBag.UserId = new SelectList(db.Users, "Id", "FullName", comment.UserId);
            return View(comment);
        }

        // GET: Comments/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        [HttpPost]
        public ActionResult DeleteComment(int id)
        {
            Comment comment = db.Comments.Find(id);
            db.Comments.Remove(comment);
            db.SaveChanges();

            return Json("ok");
        }

        // POST: Comments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Comment comment = db.Comments.Find(id);
            db.Comments.Remove(comment);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MasterScripter/MasterScripter/Controllers/ExecutionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Diagnostics;
using System.Globalization;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MasterScripter.BL.Utils;
using MasterScripter.DAL.Models;
using MasterScripter.Models;
//$('#sortable2 li').toArray().map(x=>  $(x).attr("sid") +"_"+ $(x).attr("sver")).join(",")

namespace MasterScripter.Controllers
{
    [Authorize]
    [ConnectedUserFilterAttribute]

    public class ExecutionsController : Controller
    {
        private MasterScripterContext db = new MasterScripterContext();

        // GET: Executions
        public ActionResult Index()
        {
            var user = db.Users.FirstOrDefault(u => u.Email.Equals(User.Identity.Name));

            var executions = db.Executions.Include(e => e.Machine).Include(e => e.Reason).Include(e => e.User);

            if (user.Role != Role.Admin && user.Role != Role.Manager)
            {
                executions = executions.Where(e => e.Machine.CompanyCode == user.CompanyCode);
            }

            return View(executions.ToList());
        }

        // GET: Executions/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Execution execution = db.Executions.Find(id);
            if (execution == null)
            {
                return HttpNotFound();
            }
            return View(execution);
        }

        // GET: Executions/Create
        public ActionResult Create()
        {
            var user = db.Users.FirstOrDefault(u => u.Email.Equals(User.Identity.Name));

            var machines = db.Machines.Include(m => m.Company).Include(m => m.Country);

            if (user.Role != Role.Admin && user.Role != Role.Manager)
            {
                machines = machines.Where(m => m.CompanyCode == user.CompanyCode);
            }

            var grouppedScripts = db.Scripts.Include(s => s.FileType).Include(s => s.User)
                  .OrderBy(script => script.Version)
                  .GroupBy(script => script.Id).ToList();

            var scripts = grouppedScripts.Select(s => s.Last()).ToList();
            ViewBag.Scripts = scripts.ToList();
            

            ViewBag.Machines =  machines;
            ViewBag.ReasonId = new SelectList(db.Reasons, "Id", "ReasonName");
            ViewBag.UserId = new SelectList(db.Users, "Id", "FullName");
            return View();
        }
        public ActionResult GetExecutionDetail(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Execution execution = db.Executions.Find(id);
            if (execution == null)
            {
                return HttpNotFound();
            }
        
            return PartialView("Details", execution);
        }

        public ActionResult GetExecutionTimeline(ICollection<Execution> executions, ICollection<string> statuses, string order)
        {
            if (executions == null)
            {
                executions = db.Executions.Include(e => e.Machine).Include(e => e.Reason).Include(e => e.User).ToList();
            }

            var user = db.Users.FirstOrDefault(u => u.Email.Equals(User.Identity.Name));

            if (user.Role != Role.Admin && user.Role != Role.Manager)
            {
                executions = executions.Where(e => e.Machine.CompanyCode == user.CompanyCode).ToList();
            }

            List<Status> statusesList = statuses.ToList().ConvertAll(status =>
            {
                Status s;
                return Enum.TryParse(status.Replace(" ", string.Empty), true, out s) ? s : Status.Running;
            });

            executions = executions
                .Where(execution => statusesList.Contains(execution.Status))
                .OrderBy(execution =>
                {
                    switch (order.Replace(" ", string.Empty))
                    {
                        case "endtime":
                            return execution.EndTime;
                        case "scheduletime":
                            return execution.ScheduleTime;
                        case "srarttime":
                        case "starttime":
                            return execution.SrartTime;
                        case "creationdate":
                        default:
                            return execution.CreationDate;
                    }
                })
                .ToList();

            return PartialView("Timeline", executions);
        }


        // POST: Executions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,CreationDate,Status,SrartTime,EndTime,ScheduleTime,UserId,ReasonId,MachineVLan,MachineIP")] Execution execution)
        {
            var user = db.Users.FirstOrDefault(u => u.Email.Equals(User.Identity.Name));

            if (ModelState.IsValid)
            {
                execution.CreationDate = DateTime.Now;
                execution.Status = Status.Waiting;

                execution.UserId = user.Id;
               
                if (!String.IsNullOrEmpty(Request.Form.Get("ScheduleTime"))){
                    execution.ScheduleTime = DateTime.ParseExact(Request.Form.Get("ScheduleTime"), "DD/MM/YYYY HH:mm", CultureInfo.InvariantCulture);
                }
                var scriptsListVal = Request.Form.Get("ScriptsList");
                if (!String.IsNullOrEmpty(scriptsListVal))
                {
                    var i = 0;
                    execution.ExecutionsScriptses = scriptsListVal.Split(',').ToList()
                        .ConvertAll(s => new ExecutionsScripts() {
                            ScriptId = int.Parse(s.Split('_')[0]),
                            ScriptVersion = int.Parse(s.Split('_')[1]),
                            Order = ++i,
                            Status = Status.Waiting
                        });
                   
                }
                db.Executions.Add(execution);
                db.SaveChanges();
                QueueManager.Instance.AddTask(execution);
                return RedirectToAction("Index");
            }

            var machines = db.Machines.Include(m => m.Company).Include(m => m.Country);

            if (user.Role != Role.Admin && user.Role != Role.Manager)
            {
                machines = machines.Where(m => m.CompanyCode == user.CompanyCode);
            }

            var grouppedScripts = db.Scripts.Include(s => s.FileType).Include(s => s.User)
                .OrderBy(script => script.Version)
                .GroupBy(script => script.Id).ToList();

            var scripts = grouppedScripts.Select(s => s.Last()).ToList();
            ViewBag.Scripts = scripts.ToList();


            ViewBag.Machines = machines;
            ViewBag.MachineIP = new SelectList(db.Machines, "IP", "IP", execution.MachineIP);
            ViewBag.ReasonId = new SelectList(db.Reasons, "Id", "ReasonName", execution.ReasonId);
            ViewBag.UserId = new SelectList(db.Users, "Id", "FullName", execution.UserId);
            return View(execution);
        }

        // GET: Executions/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Execution execution = db.Executions.Find(id);
            if (execution == null)
            {
                return HttpNotFound();
            }
            ViewBag.MachineIP = new SelectList(db.Machines, "IP", "IP", execution.MachineIP);
            ViewBag.ReasonId = new SelectList(db.Reasons, "Id", "ReasonName", execution.ReasonId);
            ViewBag.UserId = new SelectList(db.Users, "Id", "FullName", execution.UserId);
            return View(execution);
        }

        // POST: Executions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,CreationDate,Status,SrartTime,EndTime,ScheduleTime,UserId,ReasonId,MachineVLan,MachineIP")] Execution execution)
        {
            if (ModelState.IsValid)
            {
                db.Entry(execution).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MachineIP = new SelectList(db.Machines, "IP", "IP", execution.MachineIP);
            ViewBag.ReasonId = new SelectList(db.Reasons, "Id", "ReasonName", execution.ReasonId);
            ViewBag.UserId = new SelectList(db.Users, "Id", "FullName", execution.UserId);
            return View(execution);
        }

        // GET: Executions/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Execution execution = db.Executions.Find(id);
            if (execution == null)
            {
                return HttpNotFound();
            }
            return View(execution);
        }

        // POST: Executions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Execution execution = db.Executions.Find(id);
            db.Executions.Remove(execution);

MasterScripter/MasterScripter/Views/Executions/Create.cshtml
@model MasterScripter.DAL.Models.Execution

@{
    ViewBag.Title = "Create";
}
<script type="text/javascript" src="~/Scripts/Schedule.js"></script>

<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script src="~/Scripts/kmeans.js"></script>

<h2>Create</h2>
<div class="row">
    <div class="col-md-4">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            @Html.HiddenFor(model => model.MachineIP)
            @Html.HiddenFor(model => model.MachineVLan)

            <input type="text" id="ScriptsList" name="ScriptsList" style="display:none" />

            <div class="form-horizontal">
                <h4>Execution</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })


                <div class="form-group">
                    @Html.LabelFor(model => model.ScheduleTime, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <input type="text" id="ScheduleTime" class="form-control" name="ScheduleTime" />
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.ReasonId, "ReasonId", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("ReasonId", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.ReasonId, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    Machine
                    <div class="col-md-10">
                        <div class="dropdown" id="dropdownMachines">
                            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMachinesButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Select Machine
                            </button>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton" style="max-height: 20rem; overflow: auto;">
                                @foreach (var machine in ViewBag.Machines)
                                {
                                    <a class="dropdown-item" href="#" machine-ip="@machine.IP" machine-vlan="@machine.VLan">@machine.IP (@machine.VLan)</a>
                                }
                            </div>
                        </div>

                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-primary btn-lg" />
                    </div>
                </div>
            </div>
        }
    </div>
    <div class="col-md-8">
        <div class="row">
            <div class="col-md-6 jumbotron" style="padding-top:1rem; padding-bottom:1rem;">
                <h5>Script List</h5>
                <ul id="sortable1" class="connectedSortable border border-primary" style="height: 55vh; overflow: auto;    padding: 0.3rem;">
                    @foreach (var script in ViewBag.Scripts)
                    {
                        <li sid="@script.Id" sver="@script.Version" class="ui-state-default m-1" style="list-style-type: none; cursor:pointer;">
                            <div class="card text-center">
                                <div class="card-body">
                                    <h5 class="card-title">@script.Name (@script.Version)</h5>
                                    <p class="card-text">@script.Description</p>
                                </div>
                            </div>
                        </li>
                    }
                </ul>
            </div>
            <div class="col-md-6 jumbotron" style="padding-top:1rem; padding-bottom:1rem;">
                <h5>Scripts to Execution</h5>
                <ul id="sortable2" class="connectedSortable border border-primary" style="height: 55vh; overflow: auto;     padding: 0.3rem;"></ul>
                <h6 id="scriptsCount" >Total Scripts: 0</h6>
            </div>
        </div>
    </div>
</div>



<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

<script type="text/javascript">
    $(function () {
        // set on click event for each element item
        $("#dropdownMachines .dropdown-menu  a.dropdown-item").click(function () {

            // update the text of the seleced item
            $("#dropdownMachinesButton").text($(this).text());
            $("#dropdownMachinesButton").val($(this).text());

            // update the IP and the VLan data
            $("#MachineVLan").val($(this).attr("machine-vlan"));
            $("#MachineIP").val($(this).attr("machine-ip"));
        });
    });

    $(function () {
        $("#sortable1, #sortable2").sortable({
            connectWith: ".connectedSortable",
            update: function (event, ui) {
                $("#ScriptsList").val($('#sortable2 li').toArray().map(x => $(x).attr("sid") + "_" + $(x).attr("sver")).join(","));
                $('#scriptsCount').text('Total Scripts: ' + $('#sortable2 li').length);
     

                if (isKmenasData === false) {
                    getKmenasData();
                }
            
            }
           
            
        }).disableSelection();
    });

    var isKmenasData = false;

    function getKmenasData() {
        isKmenasData = true;
        $('#sortable1 li .card-body').removeClass('bg-info');
        $('#sortable2 li .card-body').removeClass('bg-info');


        $.get('@Url.Action("GetKmeansData","Analytics")').success(function (parameters) {

            var km = new kMeans({K: 4 });

            var data = parameters.data.map(x => x.Item2);

            var fakeExe = Array.apply(null, Array(data[0].length)).map(Number.prototype.valueOf, 0);
            $('#sortable2 li').toArray().map(x => parseInt($(x).attr("sid"))).forEach(x => fakeExe[x] = 1);

            data.push(fakeExe);

            km.cluster(data);

            while (km.step()) {
                km.findClosestCentroids();
                km.moveCentroids();

                console.log(km.centroids);

                if (km.hasConverged()) break;
            }

            console.log('Finished in:', km.currentIteration, ' iterations');
            console.log(km.centroids, km.clusters);

            var matchedCluster = km.clusters.filter(x => x.indexOf(data.length - 1) > -1);

            var scriptCounter = Array.apply(null, Array(data[0].length)).map(Number.prototype.valueOf, 0);

            matchedCluster[0].forEach(x => {
                if (parameters.data[x]) {
                    parameters.data[x].Item2.forEach((temp, i) => {
                        scriptCounter[i] += temp;
                    });
                }
            });

            var tempArray = scriptCounter;
            tempArray = tempArray.filter((x, i) => fakeExe[i] === 0);
            tempArray.sort((a, b) => b-a);

            var suggestedScriptId = scriptCounter.indexOf(tempArray[0]);

            $('#sortable1 li[sid='+suggestedScriptId+'] .card-body').addClass('bg-info');
            $("#sortable1").scrollTo(".bg-info", 1000);
            isKmenasData = false;
        });


    }

    $('#ScheduleTime').bootstrapMaterialDatePicker({ format: 'DD/MM/YYYY HH:mm',minDate: new Date() });
</script>

MasterScripter/MasterScripter/Views/Executions/Delete.cshtml
@model MasterScripter.DAL.Models.Execution

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Execution</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Machine.IP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Machine.IP)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Reason.ReasonName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Reason.ReasonName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.User.FullName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.FullName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreationDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreationDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SrartTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SrartTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ScheduleTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ScheduleTime)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MasterScripter/MasterScripter/Views/Executions/Index.cshtml
@using System.Linq.Expressions
@using MasterScripter.DAL.Models
@model IEnumerable<MasterScripter.DAL.Models.Execution>

@{
    ViewBag.Title = "Index";
}

@functions{

    public string GetIconText(Status status)
    {
        switch (status)
        {
            case Status.Running:
                return "directions_run";
            case Status.Succeeded:
                return "done";
            case Status.Failed:
                return "error_outline";
            case Status.Waiting:
            default:
                return "access_time";
        }
    }

    public string GetCssClass(Status status, string prefix = "")
    {
        switch (status)
        {
            case Status.Running:
                return prefix + "primary";
            case Status.Succeeded:
                return prefix + "success";
            case Status.Failed:
                return prefix + "danger";
            case Status.Waiting:
            default:
                return prefix + "secondary";
        }
    }

}

<div class="container container-fluid">
    <div class="row">
        <div class="col-md-1">
            <i class="material-icons" data-toggle="tooltip" data-placement="top" title="Filter executions by status">filter_list</i>
        </div>
        <div class="col-md-11">
            <div class="row statuses">
                <div class="col-md-3">
                    <button type="button" aria-pressed="false" class="btn btn-block btn-outline-primary active">Running</button>
                </div>
                <div class="col-md-3">       
                    <button type="button" aria-pressed="false" class="btn btn-block btn-outline-success active">Succeeded</button>
                </div>
                <div class="col-md-3">    
                    <button type="button" aria-pressed="false" class="btn btn-block btn-outline-secondary active">Waiting</button>
                </div>
                <div class="col-md-3">    
                    <button type="button" aria-pressed="false" class="btn btn-block btn-outline-danger active">Failed</button>
                </div>
            </div>
        </div>
    </div>
    
    
    <div class="row">
        <div class="col-md-1">
            <i class="material-icons" data-toggle="tooltip" data-placement="top" title="Sotrt executions by date">sort</i>
        </div>
        <div class="col-md-11">
            <div class="row  order-time">
                <div class="col-md-3">            
                    <button type="button" aria-pressed="false" class="btn btn-block btn-info active">Creation Date</button>
                </div>
                <div class="col-md-3">          
                    <button type="button" aria-pressed="false" class="btn btn-block btn-info">Start Time</button>
                </div>
                <div class="col-md-3">        
                    <button type="button" aria-pressed="false" class="btn btn-block btn-info">End Time</button>
                </div>
                <div class="col-md-3">      
                    <button type="button" aria-pressed="false" class="btn btn-block btn-info">Schedule Time</button>
                </div>
            </div>
        </div>
    </div>
    

</div>
<div class="container container-fluid">
    <div class="page-header" id="executionsTimeline">
        <h1>Timeline</h1>
    </div>
</div>

<div class="modal fade" id="executionDetailModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel"></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">

    function updateTimeLine(collection, statuses, order) {
        var url = '@Url.Action("GetExecutionTimeline", "Executions")';

        $("#executionsTimeline").load(url, { statuses: statuses, order: order });
    }

    $('#executionDetailModal').on('show.bs.modal',
        function (event) {
            var button = $(event.relatedTarget); // Button that triggered the modal
            var data = button.data('whatever').split('_');
            var id =data[1]; // Extract info from data-* attributes


            if (data[0] === 'ExecutionConversion') {
                $('#executionDetailModal .modal-body').load('@Url.Action("GetConversion", "Comments")', { executionid: id });
                $('#exampleModalLabel').text('Execution #' + id + ' chat');


            } else {
                $('#executionDetailModal .modal-body').load('@Url.Action("GetExecutionDetail", "Executions")', { id: id });
                $('#exampleModalLabel').text('Execution #' + id + ' details');
            }


            var modal = $(this);

        });

    var statuses = $('.statuses button.active').toArray().map(elem => $(elem).text().toLowerCase());
    var order = $('.order-time button.active').first().text().toLowerCase();
    updateTimeLine(null, statuses, order);

    $(".order-time button").click(function (event) {
        var statuses = $('.statuses button.active').toArray() // get only selected (with "active" class)
            .map(elem => $(elem).text().toLowerCase()); // get the text from the buttton

        $('.order-time button.active').removeClass('active');
        $(event.target).addClass('active');

        var order = $('.order-time button.active').first().text().toLowerCase();

        updateTimeLine(null, statuses, order);
    });

    $(".statuses button").click(function (event) {
        var clickedButton = $(event.target);

        clickedButton.toggleClass('active');

        var statuses = $('.statuses button.active').toArray().map(elem => $(elem).text().toLowerCase());

        if (statuses.length === 0) {
            clickedButton.toggleClass('active');
        }

        var order = $('.order-time button.active').first().text().toLowerCase();

        updateTimeLine(null, statuses, order);
    });
</script>

<p>
    @Html.ActionLink("Create New", "Create")
</p>