MasterScripter/MasterScripter/Controllers/QueueManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MasterScripter.BL.Utils;
using MasterScripter.DAL.Models;
using MasterScripter.Models;
using Microsoft.Ajax.Utilities;

namespace MasterScripter.Controllers
{
    [Authorize]
    [ConnectedUserFilterAttribute]

    public class QueueManagerController : Controller
    {
        // GET: QueueManager
        public ActionResult Index()
        {
            return View();
        }

        // GET: QueueManager
        public ActionResult StartQueue()
        {
            QueueManager.Instance.Start();

            return Json(new { status = Status.Running}, JsonRequestBehavior.AllowGet);
        }

        public ActionResult StopQueue()
        {
            QueueManager.Instance.Stop();

            return Json(new { status = Status.Waiting }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetStatus()
        {
            Status status = QueueManager.Instance.GetStatus();
            IEnumerable<LogMessage> log = QueueManager.Instance.GetLogMessages();
            int availableThreads = QueueManager.Instance.GetAvailableThreads();
            int currentRunningTasks = QueueManager.Instance.GetCurrentRunningTasks();

            return Json(new { status = status, log = log , availableThreads  = availableThreads, currentRunningTasks = currentRunningTasks }, JsonRequestBehavior.AllowGet);
        }
        
        public ActionResult AddToTheQueue()
        {
             QueueManager.Instance.AddTask(new Execution());

            return Json(new { status = Status.Succeeded }, JsonRequestBehavior.AllowGet);
        }
    }
}

MasterScripter/MasterScripter/Controllers/ScriptsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MasterScripter.BL.Utils;
using MasterScripter.DAL.Models;
using MasterScripter.Models;

namespace MasterScripter.Controllers
{
    [Authorize]
    [ConnectedUserFilterAttribute]

    public class ScriptsController : Controller
    {
        private MasterScripterContext db = new MasterScripterContext();

        // GET: Scripts
        public ActionResult Index()
        {
          var grouppedScripts = db.Scripts.Include(s => s.FileType).Include(s => s.User)
                .OrderBy(script => script.Version)
                .GroupBy(script => script.Id).ToList();

          var  scripts = grouppedScripts.Select(s => s.Last()).ToList();
         
            return View(scripts.ToList());
        }

        public ActionResult GetScriptList(string name, string desc, int priceRange)
        {
            var grouppedScripts = db.Scripts.Include(s => s.FileType).Include(s => s.User)
                .Where(script => (script.Name.ToLower().Contains(name.ToLower()) || string.IsNullOrEmpty(name)) &&
                                 (script.Description.ToLower().Contains(desc.ToLower()) ||
                                  string.IsNullOrEmpty(desc)) &&
                                 (priceRange == 1
                                     ? script.Cost < 100
                                     : (
                                         priceRange == 2
                                             ? (script.Cost >= 100 && script.Cost <= 500)
                                             : (priceRange == 3 ? script.Cost > 500 : true))))
                .OrderBy(script => script.Version)
                .GroupBy(script => script.Id).ToList();

            var scripts = grouppedScripts.Select(s => s.Last()).ToList();

            return PartialView("ScriptList", scripts.ToList());
        }

        public ActionResult IndexView()
        {
            var grouppedScripts = db.Scripts.Include(s => s.FileType).Include(s => s.User)
                .OrderBy(script => script.Version)
                .GroupBy(script => script.Id).ToList();

            var scripts = grouppedScripts.Select(s => s.Last()).ToList();

            return View("Index",scripts.ToList());
        }

        // GET: Scripts/Details/5
        public ActionResult Details(int? id, int? version)
        {
            if (id == null || version==null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Script script = db.Scripts.Find(id,version);
            if (script == null)
            {
                return HttpNotFound();
            }
            return View(script);
        }

        // GET: Scripts/Create
        public ActionResult Create()
        {
            ViewBag.FileTypeId = new SelectList(db.FileTypes, "Id", "Language");
            ViewBag.UserId = new SelectList(db.Users, "Id", "FullName");
            return View();
        }

        // POST: Scripts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Version,Content,Name,Description,UserId,CreationDate,Cost,FileTypeId")] Script script)
        {
            var scripts = db.Scripts.Include(s => s.FileType).Include(s => s.User);

            script.Id = scripts.Max(s => s.Id) + 1;
            script.Version = 1;
            script.CreationDate = DateTime.Now;

            var user = db.Users.FirstOrDefault(u => u.Email.Equals(User.Identity.Name));
            script.UserId = user.Id;
            ModelState["UserId"].Errors.Clear();
            ModelState.SetModelValue("UserId", new ValueProviderResult(user.Id,"",System.Globalization.CultureInfo.InvariantCulture));
            if (ModelState.IsValid)
            {
                db.Scripts.Add(script);
                db.SaveChanges();
                new TwitterAPI().Tweet(string.Format("The script {0} - {1} created. Cost: {2}$", script.Name, script.Description, script.Cost));
                return RedirectToAction("IndexView");
            }

            ViewBag.FileTypeId = new SelectList(db.FileTypes, "Id", "Language", script.FileTypeId);
            ViewBag.UserId = new SelectList(db.Users, "Id", "FullName", script.UserId);

            return View(script);
        }

        public ActionResult GetScriptDetail(int? id, int? version)
        {
            if (id == null || version == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Script script = db.Scripts.Find(id, version);
            if (script == null)
            {
                return HttpNotFound();
            }
            ViewBag.FileTypeId = new SelectList(db.FileTypes, "Id", "Language", script.FileTypeId);
            ViewBag.UserId = new SelectList(db.Users, "Id", "FullName", script.UserId);

            return PartialView("Details", script);
        }

        // GET: Scripts/Edit/5
        public ActionResult Edit(int? id, int? version)
        {
            if (id == null || version==null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Script script = db.Scripts.Find(id,version);
            if (script == null)
            {
                return HttpNotFound();
            }
            ViewBag.FileTypeId = new SelectList(db.FileTypes, "Id", "Language", script.FileTypeId);
            ViewBag.UserId = new SelectList(db.Users, "Id", "FullName", script.UserId);
            return View(script);
        }

        // POST: Scripts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Version,Content,Name,Description,UserId,CreationDate,Cost,FileTypeId")] Script script)
        {
            if (ModelState.IsValid)
            {
                var user = db.Users.FirstOrDefault(u => u.Email.Equals(User.Identity.Name));
                script.UserId = user.Id;

                script.CreationDate = DateTime.Now;
                script.Version++;

                db.Scripts.Add(script);
                db.SaveChanges();
                return RedirectToAction("IndexView");
            }
            ViewBag.FileTypeId = new SelectList(db.FileTypes, "Id", "Language", script.FileTypeId);
            ViewBag.UserId = new SelectList(db.Users, "Id", "FullName", script.UserId);
            return View(script);
        }

        // GET: Scripts/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Script script = db.Scripts.Find(id);
            if (script == null)
            {
                return HttpNotFound();
            }
            return View(script);
        }

        // POST: Scripts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Script script = db.Scripts.Find(id);
            db.Scripts.Remove(script);
            db.SaveChanges();
            return RedirectToAction("IndexView");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MasterScripter/MasterScripter/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MasterScripter.BL.Utils;
using MasterScripter.DAL.Models;
using MasterScripter.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;

namespace MasterScripter.Controllers
{
    [Authorize]
    [ConnectedUserFilterAttribute]

    public class UsersController : Controller
    {
        private MasterScripterContext db = new MasterScripterContext();

        // GET: Users
        public ActionResult Index()
        {
            var users = db.Users.Include(u => u.Company);
            return View(users.ToList());
        }

        public ActionResult GetUnconnectedUsers()
        {
            // Gel all Users from our DB.
            var dbusers = db.Users.Include(u => u.Company).ToList();

            // Get all registered users (Users from the template DB).
            var users = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>().Users.ToList(); 

            // Get the new Users (unconnected) -
            // Filter the Users that exist in the template DB and not exist in our DB (Filter by email)
            // And create a new list of Users (our model)
            var unconnectedUserst = users
                .Where(u=>!dbusers.Any(dbu=>dbu.Email.ToLower().Equals(u.Email.ToLower()))).ToList() // emails that don't exist
                .ConvertAll(u=>new User() // convert to our User object model
                {
                    FullName = u.UserName,
                    Email = u.Email,
                    IsDeleted = true
                });

            // Send to the View a "Flag" that indicates that this is a Unconected users list
            ViewBag.IsUnconnectedUsers = true;

            // Return the Indec view BUT(!!) send the genreated list
            return View("Index", unconnectedUserst.ToList());
        }

        // GET: Users/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // GET: Users/Create
        public ActionResult Create()
        {
            ViewBag.CompanyCode = new SelectList(db.Companies, "Code", "Name");
            return View();
        }

        // GET: Users/Create
        public ActionResult Connect(string username, string email) // same as Create, but send known data.
        {
            ViewBag.CompanyCode = new SelectList(db.Companies, "Code", "Name");
            ViewBag.UserName = username;
            ViewBag.Email = email;

            return View("Create");
        }

        // POST: Users/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,FullName,Email,Role,IsDeleted,CompanyCode,CreationDate")] User user)
        {
            if (ModelState.IsValid)
            {
                user.CreationDate = DateTime.Now;
                user.IsDeleted = false;
                db.Users.Add(user);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CompanyCode = new SelectList(db.Companies, "Code", "Name", user.CompanyCode);
            return View(user);
        }

        // GET: Users/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            ViewBag.CompanyCode = new SelectList(db.Companies, "Code", "Name", user.CompanyCode);
            return View(user);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,FullName,Email,Role,IsDeleted,CompanyCode,CreationDate")] User user)
        {
            if (ModelState.IsValid)
            {
                db.Entry(user).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CompanyCode = new SelectList(db.Companies, "Code", "Name", user.CompanyCode);
            return View(user);
        }

        // GET: Users/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            User user = db.Users.Find(id);
            db.Users.Remove(user);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MasterScripter/MasterScripter/Views/Shared/NotConnectedYet.cshtml
@{
    ViewBag.Title = "NotConnectedYet";

}

<div class="container container-fluid">
    <div class="jumbotron">
        <h1 class="display-4">You are not authorized yet!</h1>
        <p class="lead">Please contact to Admin to get permissions.</p>
        <hr class="my-4">
        <p>Take the time to read something on the news.</p>
      
    </div>

    <div class="container-fluid loading-div" id="loadingNews"></div>
    <div class="card-columns" style="column-count: 4; column-gap: 0;" id="cards">

    </div>
    
    <section>
        <canvas id="myCanvas" width="200" height="100" style="border:1px solid #000000;"></canvas>

    </section>
</div>

<script type="text/javascript">
    // combine URL with API_KEY and paramters
    var url = 'https://newsapi.org/v2/top-headlines?' +
        'country=us&' +
        'category=technology&' +
        'apiKey=bfc10777d8424d098c4f04f1a6abf89e';

    $.get(url).success(data => { // get all news from BBC
        data.articles.forEach(article => { // for each result, create card with title button and image
            var card = '<div class="container container-fluid">' +
                '<div class="card">' +
                (article.urlToImage !== null ? ('<img class="card-img-top" src="' + article.urlToImage + '" alt="' + article.title + '">') : "") +
                '<div class="card-body">' +
                '<h5 class="card-title">'+article.title+'</h5>' +
                '<h6 class="card-subtitle mb-2 text-muted"><span data-date="' + article.publishedAt + '">' + article.publishedAt + '</span> - ' +
                '<cite title="' + article.source.name + '">' + article.source.name + '</cite>' +
                '</h6>' +
                (article.description !==null ? ('<p class="card-text">'+article.description+'</p>'): "") +
                '<a href="'+article.url+'" class="card-link">Go to article</a>' +
                '</div>' +
                '</div>' +
                '</div>';

            $('#cards').append(card); // apend the element
        });

        $(function () {
            $('[data-date]').each(function () {
                var val = $(this).attr('data-date');
                if (val) {
                    $(this).html(moment(val).fromNow());
                }

            });
        });

        $('#loadingNews').hide();
    });

    var c = document.getElementById("myCanvas");
    var ctx = c.getContext("2d");
    ctx.moveTo(0, 0);
    ctx.lineTo(200, 100);
    ctx.stroke();

</script>

MasterScripter/MasterScripter/Views/Shared/SuccessPage.cshtml
@{
    ViewBag.Title = "Success";
}

<div class="jumbotron">
    <h1 class="display-4">The @(ViewBag.ModelName + " " + ViewBag.ItemName), saved successfully!</h1>
    <i class="material-icons md-48 text-success">done</i>
</div>

<script type="text/javascript">
    setTimeout(function() {
            $('.modal').modal('toggle');
        },
        1000);
</script>

MasterScripter/MasterScripter/Views/Shared/_Layout.cshtml
@using System.Web.Script.Serialization
@using MasterScripter.Models
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")


    @Scripts.Render("~/bundles/popper")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script type="text/javascript" src="@Url.Content("~/Scripts/moment.js")"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.4.1/ace.js"></script>
    <script type="text/javascript">
        jQuery.fn.scrollTo = function (elem, speed) {
            $(this).animate({
                scrollTop: $(this).scrollTop() - $(this).offset().top + $(elem).offset().top
            }, speed == undefined ? 1000 : speed);
            return this;
        };
    </script>

    @RenderSection("scripts", required: false)

</head>
<body>
<nav style="position: fixed; width: 100%; z-index: 999999999;">
    <div class="container-fluid bg-primary">
        <a href="@Url.Action("Index", "Home")">
            <img src="~/images/logo-1.png" class="img-fluid" alt="Responsive image" style="margin: 0.5rem 0 1rem 0; width: 13rem;">

        </a>

        <div class="" style="position: relative;">
            <div class="" style="position: absolute; left: 280px; bottom: 0;">
                <ul class="nav nav-tabs bg-primary">
                    <li class="nav-item" allow-view="0" >
                        <a class="nav-link active" href="@Url.Action("Index", "Home")">Home</a>
                    </li>
                    <li class="nav-item dropdown" allow-view="0">
                        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Scripts</a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="@Url.Action("IndexView", "Scripts")">View</a>
                            <a class="dropdown-item" allow-view="2" href="@Url.Action("Create", "Scripts")">Add new</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown" allow-view="0">
                        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Executions</a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="@Url.Action("Index", "Executions")">View</a>
                            <a class="dropdown-item" href="@Url.Action("Create", "Executions")">Add new</a>
                        </div>
                    </li>

                    <li class="nav-item dropdown" allow-view="0">
                        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Machines</a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="@Url.Action("Index", "Machines")">View</a>
                            <a class="dropdown-item" allow-view="1" href="@Url.Action("Create", "Machines")">Add new</a>
                        </div>
                    </li>
                    
                    <li class="nav-item dropdown" allow-view="2">
                        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Management</a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" allow-view="2" href="@Url.Action("Index", "Companies")">Companies</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" allow-view="2" href="@Url.Action("Index", "Users")">Users</a>
                            <a class="dropdown-item" allow-view="1" href="@Url.Action("GetUnconnectedUsers", "Users")">Unconnecte Users</a>
                            
                            <div class="dropdown-divider"></div>
                            <a id="startQueue" class="dropdown-item" href="#">Start Queue</a>
                            <a id="stopQueue" class="dropdown-item" href="#">Stop Queue</a>
                        </div>
                    </li>

                    @Html.Partial("_LoginPartial")
                </ul>
            </div>
        </div>

    </div> 
</nav>


<div class="container body-content" style="padding-top: 11rem;">
    @RenderBody()
    
    <script type="text/javascript">
        $(function() {
            $('[data-toggle="tooltip"]').tooltip();
        });

        $('#startQueue').click(function(parameters) {
            $.get('@Url.Action("StartQueue", "QueueManager")').success(function (parameters) {
                $("#startQueue").prop("disabled", true);
            });
        });

        $('#stopQueue').click(function (parameters) {
            $.get('@Url.Action("StopQueue", "QueueManager")').success(function (parameters) {
                $("#stopQueue").prop("disabled", true);
            });
        });

    </script>
    <hr/>
    <footer>
      
        <p>&copy; @DateTime.Now.Year - Dor Kfir Riman - Master Scripter Application</p>
    </footer>
</div>
    

    @functions
{

        public string GetCurrentUser()
        {
            MasterScripterContext db = new MasterScripterContext();
            MasterScripter.DAL.Models.User user = db.Users.FirstOrDefault(u => u.Email.Equals(User.Identity.Name));
            if (user != null)
            {
                return new JavaScriptSerializer().Serialize(new { id = user.Id, name= user.FullName, role= user.Role, email= user.Email });
            }

            return new JavaScriptSerializer().Serialize(new { id = "", name ="", role = "", email = "" });
        }

    }

<script type="text/javascript">

    var user = '@GetCurrentUser()';

    window.userInfo = JSON.parse(user.replace(/&quot;/g, '"'));;

    sessionStorage.setItem("userInfoId", window.userInfo.id);
    sessionStorage.setItem("userInfoName", window.userInfo.name);
    sessionStorage.setItem("userInfoRole", window.userInfo.role);
    sessionStorage.setItem("userInfoEmail", window.userInfo.email);

    //window is global fo all pages
    window.clearViews= function clearViews() {
        if (window.userInfo.role === 3) {
            $('[allow-view="1"],[allow-view="2"]').remove();
        }
        else if (window.userInfo.role === 2) {
            $('[allow-view="1"]').remove();
        }
        else if (window.userInfo.role === "") {
            $('[allow-view="0"],[allow-view="1"],[allow-view="2"]').remove();
        }
    }
    window.clearViews();
</script>

</body>
</html>