MasterScripter/MasterScripter/Controllers/AnalyticsController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Core.Objects;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MasterScripter.BL.Utils;
using MasterScripter.DAL.Models;
using MasterScripter.Models;

namespace MasterScripter.Controllers
{
    [Authorize]
    [ConnectedUserFilterAttribute]
    public class AnalyticsController : Controller
    {
        private MasterScripterContext db = new MasterScripterContext();

        // GET: Analytics
        public ActionResult Index()
        {
            var user = db.Users.FirstOrDefault(u => u.Email.Equals(User.Identity.Name));

            List<Execution> executions = db.Executions.ToList();
            List<Machine> machines = db.Machines.ToList();

            if (user.Role != Role.Admin && user.Role != Role.Manager)
            {
                executions = executions.Where(e => e.Machine.CompanyCode == user.CompanyCode).ToList();
                machines = machines.Where(m=>m.CompanyCode == user.CompanyCode).ToList();
            }

            Dictionary<Status, int> totalStatuses = executions.GroupBy(execution => execution.Status)
                .ToList().ToDictionary(input => input.Key, grouping => grouping.Count());

            Dictionary<Reason, int> totalReasons = executions.GroupBy(execution => execution.Reason)
                .ToList().ToDictionary(input => input.Key, grouping => grouping.Count());

            Dictionary<Country, int> totalCountries = machines.GroupBy(execution => execution.Country)
                .ToList().ToDictionary(input => input.Key, grouping => grouping.Count());

            Dictionary<Machine, int> totalMachine = executions.GroupBy(execution => execution.Machine)
                .ToList().ToDictionary(input => input.Key, grouping => grouping.Count());


            var myData = from log in executions
                         group log by log.CreationDate.Value.Date into g
                orderby g.Key
                select new { CreateTime = g.Key, Count = g.Count() };


            Tuple<int, int, int> states = new Tuple<int, int, int>(machines.Count(),
                machines.Count(m => !m.IsDeleted),
                machines.Count(m => m.IsDeleted));
          

            Dictionary<DateTime, int> totalExecutionsPerDay = myData.ToList().Where(i=>i.CreateTime!=null).ToDictionary(i=>(DateTime)i.CreateTime, i=>i.Count);

            AnalyticsViewModel analyticsViewModel = new AnalyticsViewModel()
            {
                TotalStatuses =  totalStatuses,
                TotalCountries = totalCountries,
                TotalReasons = totalReasons,
                TotalExecutionsPerDay = totalExecutionsPerDay,
                TotalMachines = totalMachine,
                MachinesState = states
            };

            return PartialView(analyticsViewModel);
        }

        public ActionResult GetKmeansData()
        {
            List<Tuple<int, int[]>> ff = new List<Tuple<int, int[]>>();

            int sctiptCount = db.Scripts.Max(s => s.Id) + 1;

            var features = db.Executions.ToList().ConvertAll<Tuple<int, int[]>>(input =>
            {
                var arr = new int[sctiptCount];
                for (int i = 0; i < arr.Length; i++)
                    arr[i] = input.ExecutionsScriptses.Any(s => s.ScriptId == i) ? 1 : 0;

                return new Tuple<int, int[]>(input.Id, arr);
            }).ToList();

            return Json(new {data = features }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetLogger()
        {
            return PartialView("Logger");
        }
    }
}

MasterScripter/MasterScripter/Controllers/HomeController.cs
using MasterScripter.BL.Utils;
using MasterScripter.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MasterScripter.Controllers
{
    [Authorize]
    [ConnectedUserFilterAttribute]
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            MasterScripterContext db = new MasterScripterContext();
            MasterScripter.DAL.Models.User user = db.Users.FirstOrDefault(u => u.Email.Equals(User.Identity.Name));
            if (user != null)
            {
                return View();
            }
            return View("NotConnectedYet");
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult NotConnectedYet()
        {
            //ViewBag.Message = "Your application description page.";

            return View("NotConnectedYet");
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

MasterScripter/MasterScripter/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

MasterScripter/MasterScripter/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MasterScripter/MasterScripter/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
<video id="background-video" src="~/videos/staticsvideo.mp4" type="video/mp4" autoplay loop muted></video>

<div class="container-fluid" allow-view="0">
    <div class="card" style="margin-bottom: 5px;">
        <div class="card-body">
            <div id="loggerPlaceHolder"></div>
        </div>
    </div>
</div>

<div class="container-fluid" allow-view="0">
    <div class="row">
        <div class="col-4">
            <div class="card" style="margin-bottom: 5px;">
                <div class="card-body">
                    <a class="twitter-timeline" data-width="350" data-height="600" href="https://twitter.com/dorkfirroman?ref_src=twsrc%5Etfw">Tweets by dorkfirroman</a>
                    <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
                </div>
            </div>
        </div>
        <div class="col-8" id="analytics-view-numbers-place-holder">
         
        </div>
    </div>
  
</div>
    <div id="analytics-view" allow-view="0"></div>

    <script type="text/javascript">

    $('#analytics-view').load('@Url.Action("Index","Analytics")');

    $('#loggerPlaceHolder').load('@Url.Action("GetLogger","Analytics")',
        function (parameters) {
            setTimeout(function(parameters) {
                    var elem = $('#analytics-view-numbers').detach();
                    $('#analytics-view-numbers-place-holder').append(elem);
                },
                1000);
       
        });
    </script>